### ISSUE TITLE
So.. where is the viz? :D

### ISSUE THREAD

**Issue by abitrolly** [rse-ops/vis-experiment#1]

**Comment by vsoch** [comment]
It’s a work in progress, lol. Patience. 🧘‍♂️

**Comment by abitrolly** [comment]
![image](https://user-images.githubusercontent.com/8781107/199408218-ee32fe4f-2a4e-423a-8d9a-83d7c0d06528.png)

**Comment by vsoch** [comment]
❤️ 🐻

**Comment by vsoch** [comment]
@abitrolly so to keep you in the loop - I have scripts that convert the caliper output to csv formatted (or whatever we like really) and the strategy I want to take now is using grafana. I have it loaded as a data source, but I don't understand the use cases ;/ graphs that someone would want to see, and more specifically how that maps to the caliper output. Do you have a sense?

**Comment by abitrolly** [comment]
It it is this Caliper - http://software.llnl.gov/Caliper/ - which is about performance analysis, then I'd expect some performance graphs like https://observablehq.com/@cimi/jfr-flamegraph?collection=@cimi/java-mission-control from it.

**Comment by vsoch** [comment]
Perfecto! I'll do that one first.

**Comment by vsoch** [comment]
okay got a basic flamegraph, although the structure is wrong. I think we should use the work by Pascal that has gone into spot for these vis, so my gameplan now is to first do this https://github.com/LLNL/spotbe/issues/18 and then start to refactor what is currently spot into a more streamlined thing that just loads from the database and then makes the graphs.

**Comment by abitrolly** [comment]
Hmm... Performance visualization libraries without visualizations don't look good. Obviously. :D

**Comment by vsoch** [comment]
Are you here just to troll me? I don’t appreciate it.

**Comment by abitrolly** [comment]
The username should check out if I do, but I am actually speaking of https://github.com/LLNL/spotbe and related repos that lack examples.

**Comment by vsoch** [comment]
Going to close this issue, thanks for your interest @abitrolly.

**Comment by abitrolly** [comment]
Ping me once you have some screens. There is no way I could use that myself, but I am curious to see what LLNL is cooking.
